# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logdapp', '0002_auto_20171012_1222'),
    ]

    operations = [
    ]
