# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logdapp', '0003_auto_20171012_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grade', models.CharField(max_length=2)),
                ('Course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logdapp.Courses')),
                ('Prof_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logdapp.Prof')),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logdapp.Students')),
            ],
        ),
    ]
